### ISSUE TITLE
Selfharm Linux deletes libpcre, so that find no longer works

### ISSUE THREAD

**Issue by ghost** [RGBCube/selfharm-linux#3]
![image](https://user-images.githubusercontent.com/69681150/186864585-4f2553d1-aaf8-40f5-bfa4-339253149171.png)
Here is a screenshot
Selfharm Linux should not delete find and its libraries. Why? Because

**Comment by RGBCube** [comment]
skill issue 
its doing what it's supposed to do

**Comment by ghost** [comment]
didn't ask
